version: "3.7"
services:
  python-api:
    build: python-api
    networks:
      - microservices
    container_name: dev-python-api
    ports:
      - 5000:5000
    # env_file:
    #   - python-api/.env
    volumes:
      - ./python-api:/api
  node-api:
    networks:
      - microservices
    build: node-api
    container_name: dev-node-api
    ports:
      - 3000:3000
    # env_file:
    #   - node-api/.env

networks:
  microservices: